algoritmo "Procedimentos"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var

n:caractere

Procedimento texto(nome:caractere)
inicio
escreval("Bom dia, ",nome,"!")
fimprocedimento

inicio

escreva("Digite seu nome: ")
leia(N)
texto(n)

fimalgoritmo